name: melanoma_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.5.3
  - numpy=1.23.5
  - scikit-learn=1.2.2
  - matplotlib=3.6.0
  - seaborn=0.13.2
  - xgboost=2.1.1
  - joblib=1.2.0
  - pip
  - pip:
      - pycaret==3.2.0
      - optuna==4.4.0
